version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18.20.4
    commands:
      - echo Installing dependencies...
      - npm ci

  build:
    commands:
      - echo Building the React app...
      - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: ${ARTIFACTS_BASE_DIRECTORY:-dist}
  discard-paths: no
